# Generated by Django 5.0.4 on 2024-05-23 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('cod_perm', models.AutoField(primary_key=True, serialize=False)),
                ('nom_perm', models.CharField(max_length=50)),
                ('des_perm', models.CharField(max_length=220)),
                ('est_perm', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('cod_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(max_length=50)),
                ('est_rol', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cod_per', models.AutoField(primary_key=True, serialize=False)),
                ('nom_per', models.CharField(max_length=50)),
                ('ape_per', models.CharField(max_length=50)),
                ('cor_per', models.EmailField(max_length=254, unique=True)),
                ('est_per', models.CharField(max_length=1)),
                ('fky_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cod_usu', models.AutoField(primary_key=True, serialize=False)),
                ('cor_usu', models.EmailField(max_length=254, unique=True)),
                ('con_usu', models.CharField(max_length=50)),
                ('est_usu', models.CharField(max_length=1)),
                ('fky_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.persona')),
                ('fky_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.rol')),
            ],
        ),
    ]
