# Generated by Django 5.0.4 on 2024-09-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cat', models.CharField(max_length=50)),
                ('est_cat', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('cod_mar', models.AutoField(primary_key=True, serialize=False)),
                ('nom_mar', models.CharField(max_length=50)),
                ('est_mar', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=50)),
                ('pre_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_prod', models.CharField(max_length=1)),
                ('fky_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
                ('fky_mar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('cod_prod_cat', models.AutoField(primary_key=True, serialize=False)),
                ('est_prod_cat', models.CharField(max_length=1)),
                ('fky_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
                ('fky_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'unique_together': {('fky_prod', 'fky_cat')},
            },
        ),
        migrations.CreateModel(
            name='ProductoMarca',
            fields=[
                ('cod_prod_mar', models.AutoField(primary_key=True, serialize=False)),
                ('est_prod_mar', models.CharField(max_length=1)),
                ('fky_mar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.marca')),
                ('fky_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'unique_together': {('fky_prod', 'fky_mar')},
            },
        ),
    ]
