# Generated by Django 5.0.4 on 2024-09-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_est_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='est_cat',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='marca',
            name='est_mar',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1),
        ),
    ]
