# Generated by Django 5.1 on 2024-09-03 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cod_per', models.AutoField(primary_key=True, serialize=False)),
                ('nom_per', models.CharField(max_length=50)),
                ('ape_per', models.CharField(max_length=50)),
                ('cor_per', models.EmailField(max_length=50, unique=True)),
                ('est_per', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('cod_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(max_length=50)),
                ('est_rol', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('cod_tip_per', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tip_per', models.CharField(max_length=50)),
                ('est_tip_per', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cli', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=50)),
                ('ape_cli', models.CharField(max_length=50)),
                ('cor_cli', models.EmailField(max_length=50)),
                ('con_cli', models.CharField(max_length=50)),
                ('est_cli', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fky_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('cod_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prov', models.CharField(max_length=50)),
                ('ape_prov', models.CharField(max_length=50)),
                ('cor_prov', models.EmailField(max_length=50)),
                ('con_prov', models.CharField(max_length=50)),
                ('est_prov', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fky_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='fky_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.rol'),
        ),
    ]
