# Generated by Django 5.1 on 2024-09-03 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='fky_per',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fky_rol',
        ),
        migrations.AddField(
            model_name='persona',
            name='fky_tip_per',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personas.tipopersona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='est_per',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='tipopersona',
            name='est_tip_per',
            field=models.CharField(max_length=1),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
