# Generated by Django 5.0.4 on 2024-09-17 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_remove_proveedor_fky_per_remove_persona_fky_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ape_per',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Solo se permiten letras y espacios.')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nom_per',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Solo se permiten letras y espacios.')]),
        ),
    ]
